# Builds every derived copy of the crash reporter's app icon from ONE source: AppIcon.png.
#
# WHY A SCRIPT AND NOT CHECKED-IN ART. There are three consumers - the .exe icon Explorer shows
# (AppIcon.ico via the .rc), the window/taskbar icon GLFW takes as RGBA pixels, and the bug drawn
# in our own title bar - and hand-exporting three files is how they drift apart. This regenerates
# all of them, so changing the icon means replacing AppIcon.png and re-running:
#
#     powershell -File Tools/CrashReporter/Resources/make_app_icon.ps1
#
# Outputs, next to this script: AppIcon.ico (16/32/48/256, PNG-compressed entries, Vista and
# later) and Icon/AppIcon.gen.hpp (16/32/48 straight-alpha RGBA8 for glfwSetWindowIcon and the
# title bar). The downscale is HighQualityBicubic on a 32bppArgb surface: a naive shrink of a
# 1254 px source to 16 px turns the artwork to mud at exactly the size that matters most.

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourcePath = Join-Path $here 'AppIcon.png'
if (-not (Test-Path $sourcePath)) { throw "the source artwork is missing: $sourcePath" }
$outDir = Join-Path $here 'Icon'
if (-not (Test-Path $outDir)) { [void](New-Item -ItemType Directory -Path $outDir) }

$source = [System.Drawing.Bitmap]::FromFile($sourcePath)
"source $($source.Width)x$($source.Height) $($source.PixelFormat)"

$sizes = @(16, 32, 48, 256)
$bitmaps = @{}
foreach ($size in $sizes) {
    $bmp = New-Object System.Drawing.Bitmap $size, $size, ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.CompositingMode = [System.Drawing.Drawing2D.CompositingMode]::SourceCopy
    $g.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
    $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
    # SourceCopy keeps the source's own alpha instead of compositing it onto opaque black, which
    # is what produces the black fringe a taskbar icon shows when it is done the naive way.
    $attr = New-Object System.Drawing.Imaging.ImageAttributes
    $attr.SetWrapMode([System.Drawing.Drawing2D.WrapMode]::TileFlipXY)
    $rect = New-Object System.Drawing.Rectangle 0, 0, $size, $size
    $g.DrawImage($source, $rect, 0, 0, $source.Width, $source.Height, [System.Drawing.GraphicsUnit]::Pixel, $attr)
    $g.Dispose()
    $bitmaps[$size] = $bmp
}
$source.Dispose()

# ---- AppIcon.ico -------------------------------------------------------------------------------
$payloads = @{}
foreach ($size in $sizes) {
    $ms = New-Object System.IO.MemoryStream
    $bitmaps[$size].Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
    $payloads[$size] = $ms.ToArray()
    $ms.Dispose()
}
$icoPath = Join-Path $here 'AppIcon.ico'
$out = New-Object System.IO.MemoryStream
$w = New-Object System.IO.BinaryWriter $out
$w.Write([UInt16]0); $w.Write([UInt16]1); $w.Write([UInt16]$sizes.Count)
$offset = 6 + (16 * $sizes.Count)
foreach ($size in $sizes) {
    $w.Write([Byte]($size % 256)); $w.Write([Byte]($size % 256)); $w.Write([Byte]0); $w.Write([Byte]0)
    $w.Write([UInt16]1); $w.Write([UInt16]32)
    $w.Write([UInt32]$payloads[$size].Length); $w.Write([UInt32]$offset)
    $offset += $payloads[$size].Length
}
foreach ($size in $sizes) { $w.Write($payloads[$size]) }
$w.Flush()
[System.IO.File]::WriteAllBytes($icoPath, $out.ToArray())
$w.Dispose(); $out.Dispose()
"wrote $icoPath ($((Get-Item $icoPath).Length) bytes)"

# ---- Icon/AppIcon.gen.hpp ----------------------------------------------------------------------
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// GENERATED by Tools/CrashReporter/Resources/make_app_icon.ps1 - DO NOT EDIT.')
[void]$sb.AppendLine('// Re-run that script after replacing AppIcon.png; it writes AppIcon.ico from the same')
[void]$sb.AppendLine('// pixels, which is what keeps the window icon, the title bar and the .exe icon one image.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// Mutable on purpose: GLFWimage takes a non-const pointer. GLFW only reads it.')
[void]$sb.AppendLine('namespace CrashReporter::AppIcon')
[void]$sb.AppendLine('{')
foreach ($size in @(16, 32, 48)) {
    $bmp = $bitmaps[$size]
    $data = $bmp.LockBits((New-Object System.Drawing.Rectangle 0, 0, $size, $size),
        [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
        [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $bytes = New-Object byte[] ($data.Stride * $size)
    [System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $bytes, 0, $bytes.Length)
    $bmp.UnlockBits($data)
    [void]$sb.AppendLine("    // $($size)x$($size) RGBA8, straight alpha")
    [void]$sb.AppendLine("    inline unsigned char kPixels$size[$($size * $size * 4)] = {")
    $line = New-Object System.Text.StringBuilder
    $count = 0
    for ($y = 0; $y -lt $size; $y++) {
        for ($x = 0; $x -lt $size; $x++) {
            $i = ($y * $data.Stride) + ($x * 4)
            # GDI+ hands back BGRA; GLFW and OpenGL want RGBA.
            foreach ($v in @($bytes[$i + 2], $bytes[$i + 1], $bytes[$i], $bytes[$i + 3])) {
                if ($count -eq 0) { [void]$line.Append('        ') } else { [void]$line.Append(' ') }
                [void]$line.Append("$v,")
                $count++
                if ($count -eq 24) { [void]$sb.AppendLine($line.ToString()); $line.Clear() | Out-Null; $count = 0 }
            }
        }
    }
    if ($count -gt 0) { [void]$sb.AppendLine($line.ToString()) }
    [void]$sb.AppendLine('    };')
    [void]$sb.AppendLine('')
}
[void]$sb.AppendLine('} // namespace CrashReporter::AppIcon')
$hppPath = Join-Path $outDir 'AppIcon.gen.hpp'
[System.IO.File]::WriteAllText($hppPath, $sb.ToString().Replace("`r`n", "`n"))
foreach ($size in $sizes) { $bitmaps[$size].Dispose() }
"wrote $hppPath ($((Get-Item $hppPath).Length) bytes)"
