project "Common"
    kind "StaticLib"

    -- THE VERSION IS GENERATED BY THE BUILD, NOT BY ONE WRAPPER SCRIPT.
    --
    -- Until 2026-09-07 `scripts/GenVersion.sh` had exactly one caller, `scripts/MacOS/BuildMacOS.sh`,
    -- and its Windows twin had exactly one, `scripts\Windows\Setup.bat` — a script that runs once per
    -- machine. Everyone who builds with `make` or `msbuild` directly (agents, the BuildSlot queue, the
    -- Windows CI job, the owner) therefore compiled whatever `Version.gen.hpp` was lying on disk: the
    -- header in the main tree said commit **492** while the repository stood at **1233**. The
    -- generator's own frugality — it rewrites the file only when the content changes, so an unchanged
    -- version relinks nothing — is what kept that invisible for a month, and it is still right.
    --
    -- THIS project and not the ones that display the version: `Version.cpp` lives here, and every
    -- target that shows a build number (Editor, Runtime, the tools, every test suite) links Common, so
    -- one hook reaches all of them and nothing added later can miss it.
    --
    -- WHY TWO SPELLINGS, AND WHY NOT `prebuildcommands` ON BOTH. `prebuildcommands` was the first thing
    -- tried and it is WRONG FOR MAKE, in a way that only shows up in parallel builds. gmake2 hangs the
    -- prebuild off `$(OBJECTS): | prebuild` inside Common.make; with `-j` GNU make stats the remaining
    -- prerequisites of an object WHILE that order-only recipe is still in flight, caches the header's
    -- pre-generation timestamp, and then decides `Version.o` is up to date against a header that has
    -- since changed. Measured here, one variable at a time, on 2026-09-07 with a fresh commit each time:
    --   -j1 -> header 11:24:04, Version.o 11:24:05  (recompiled, correct)
    --   -j4 -> header 11:24:11, Version.o 11:24:05  (NOT recompiled; the version landed one build late)
    -- "Right if you build twice" is the same defect one lag shorter, so it cannot ship.
    --
    -- `makesettings` puts the generator in the makefile's own text, where `$(shell ...)` runs while the
    -- makefile is being READ — before make has stat'ed anything at all, and before the `.d` files at the
    -- bottom of Common.make are even included. There is no window for a cached timestamp to exist in.
    -- Verified at -j4: header 11:26:01, Version.o 11:26:02, one run.
    --
    -- MSBuild has no such window and needs no such trick: PreBuildEvent runs before ClCompile, and
    -- ClCompile does its own up-to-date check inside itself, after the header is already refreshed. So
    -- Windows keeps the ordinary `prebuildcommands`, which is also the only one of the two that MSBuild
    -- understands — `makesettings` is a make-exporter setting and the vs2022 exporter ignores it.
    filter "system:not windows"
        makesettings [[
DESERT_VERSION_LOG := $(shell bash ./scripts/GenVersion.sh)
ifneq (,$(DESERT_VERSION_LOG))
  $(info $(DESERT_VERSION_LOG))
endif
]]
    filter "system:windows"
        prebuildcommands { 'call "%{wks.location}\\scripts\\Windows\\GenVersion.bat"' }
    filter {}

    files {
        "Source/Common/**.cpp",
        "Source/Common/**.hpp",
        -- The shared project-format serializer lives in the desert-shared submodule (one definition
        -- for the engine and the launcher); the ENGINE compiles it into Common, the launcher
        -- compiles the same file itself. Missing file here means an uninitialized submodule:
        -- `git submodule update --init ThirdParty/desert-shared`.
        "%{wks.location}/ThirdParty/desert-shared/Source/ProjectFormat.cpp",
        "%{wks.location}/ThirdParty/desert-shared/Source/EngineRegistry.cpp",
    }

    includedirs {
        "Source/",
        "Source/Common",
    }
    
    for name, path in pairs(deps.Common.IncludeDir) do
        externalincludedirs { path }
    end
    
    for name, path in pairs(deps.CommonSpecific.IncludeDir) do
        externalincludedirs { path }
    end
    
    links { "Optick" }
    
    for _, define in ipairs(deps.Common.Defines) do
        defines { define }
    end
    
    for _, define in ipairs(deps.CommonSpecific.Defines) do
        defines { define }
    end

    filter "configurations:Debug"
        defines { "DESERT_CONFIG_DEBUG" }
        symbols "On"

    filter "configurations:Release"
        defines { "DESERT_CONFIG_RELEASE" }

    filter { "system:windows" }
        defines { "DESERT_PLATFORM_WINDOWS" }
        files {
            "Source/Common/Platform/Windows/**.cpp",
            "Source/Common/Platform/Windows/**.hpp",
        }

    -- The Source/Common/** glob above already picks the Windows platform sources
    -- up on every OS — drop them when not targeting Windows.
    filter { "system:not windows" }
        removefiles {
            "Source/Common/Platform/Windows/**",
        }

    filter { "system:macosx" }
        defines { "DESERT_PLATFORM_MACOS" }
        files {
            "Source/Common/Platform/MacOS/**.cpp",
            "Source/Common/Platform/MacOS/**.hpp",
            "Source/Common/Platform/MacOS/**.mm",
        }

    filter {}