// AUTO-GENERATED by DesertHeaderTool. DO NOT EDIT.
// Regenerated on every build from REFLECT()/PROPERTY() annotations: the reflected types of ONE module
// (BuildScripts/DesertModules.lua), registered by Reflection.gen.cpp in the module table's order.
{# The emitter's line wrapping is not clang-format-stable across versions (the CI gate runs a different
   clang-format than developers), so the whole file is excluded from formatting. Keeps the "changed lines"
   format gate green when an enum/field change regenerates these long initializers. -#}
// clang-format off
{# AND OUT OF THE ANALYSER FOR THE SAME REASON, one level up. The clang-tidy gate checks CHANGED LINES, and
   every line of this file changes whenever anybody adds a PROPERTY - so a diagnostic here is reported against
   a developer who did not write the line and cannot fix it in place: the file's own first line says DO NOT
   EDIT, and the next build would overwrite the fix anyway. The finding belongs to THESE templates.

   Measured 2026-09-14, adding two reflected components: the gate reported `bugprone-sizeof-container` on
   every `sizeof( T::<a std::string field> )` and `clang-diagnostic-missing-field-initializers` on every
   designated initializer that omits an optional member of PropertyMetadata - hundreds of them, none about
   the change that triggered them. The sizeof one is worth reading rather than only silencing:
   `FieldInfo::Size` for a string field is sizeof(std::string) and not the text's length, which is what the
   serializer wants, but nothing states that. -#}
// NOLINTBEGIN

{# A module without a reflected type includes nothing: its empty registration must not make it reach
   CoreReflection, which the ModuleBoundary suite would report as a crossing. -#}
{% if types %}#include <Engine/Reflection/TypeRegistrar.hpp>
#include <Engine/Reflection/ReflectionRegistry.hpp>
#include <Engine/Reflection/ContainerAccess.hpp>
#include <Engine/Reflection/ReflectionSerializer.hpp>
{% if hasFunctions %}#include <Engine/Reflection/FunctionThunk.hpp>
{% endif %}#include <cstddef>
#include <cstdint>
#include <string>
#include <type_traits>
#include <vector>

{% for inc in includes %}#include <{{ inc }}>
{% endfor %}{% endif %}
{# No static object here: a module's registration runs because the module list calls it by name, so the
   linker keeps this object for the reference and not for a side effect it cannot see (plan C11). -#}
namespace Desert::Reflection::Generated
{
void RegisterReflection_{{ module }}();

void RegisterReflection_{{ module }}()
{
{% if types %}    using namespace ::Desert::Reflection;
{% endif %}{% for t in types %}    {
        using T = ::{{ t.fqn }};
        TypeBuilder( "{{ t.registryName }}", sizeof( T ) )
            .ScriptName( "{{ t.scriptName }}" )
{% for f in t.fields %}{% include "Field.tpl" %}{% endfor %}{% for fn in t.functions %}{% include "Function.tpl" %}{% endfor %}{% for ev in t.events %}{% include "Event.tpl" %}{% endfor %}            .WithDefault<T>()
{#- ^ a default-constructed instance, so the editor can offer reset-to-default per field. #}
            .Register();
    }
{% endfor %}}
} // namespace Desert::Reflection::Generated
// NOLINTEND
