// AUTO-GENERATED by DesertHeaderTool. DO NOT EDIT.
// Regenerated on every build from REFLECT()/PROPERTY() annotations.
{# The emitter's line wrapping is not clang-format-stable across versions (the CI gate runs a different
   clang-format than developers), so the whole file is excluded from formatting. Keeps the "changed lines"
   format gate green when an enum/field change regenerates these long initializers. -#}
// clang-format off
{# AND OUT OF THE ANALYSER FOR THE SAME REASON, one level up. The clang-tidy gate checks CHANGED LINES, and
   every line of this file changes whenever anybody adds a PROPERTY - so a diagnostic here is reported against
   a developer who did not write the line and cannot fix it in place: the file's own first line says DO NOT
   EDIT, and the next build would overwrite the fix anyway. The finding belongs to THESE templates.

   Measured 2026-09-14, adding two reflected components: the gate reported `bugprone-sizeof-container` on
   every `sizeof( T::<a std::string field> )` and `clang-diagnostic-missing-field-initializers` on every
   designated initializer that omits an optional member of PropertyMetadata - hundreds of them, none about
   the change that triggered them. The sizeof one is worth reading rather than only silencing:
   `FieldInfo::Size` for a string field is sizeof(std::string) and not the text's length, which is what the
   serializer wants, but nothing states that. -#}
// NOLINTBEGIN

#include <Engine/Reflection/TypeRegistrar.hpp>
#include <Engine/Reflection/ReflectionRegistry.hpp>
#include <Engine/Reflection/ReflectionSerializer.hpp>
#include <cstddef>
#include <cstdint>
#include <string>
#include <type_traits>
#include <vector>

{% for inc in includes %}#include <{{ inc }}>
{% endfor %}
namespace
{
    struct DesertReflectionAutoRegister
    {
        DesertReflectionAutoRegister()
        {
            using namespace ::Desert::Reflection;
{% for t in types %}            {
                using T = ::{{ t.fqn }};
                TypeBuilder( "{{ t.registryName }}", sizeof( T ) )
{% for f in t.fields %}{% include "Field.tpl" %}{% endfor %}                    .WithDefault<T>()
{#- ^ a default-constructed instance, so the editor can offer reset-to-default per field. #}
                    .Register();
            }
{% endfor %}            ReflectionRegistry::Get().ResolveStructLinks();
        }
    } g_DesertReflectionAutoRegister;
}

{# Force-link anchor: this TU lives in a static lib, so its static initializer (the registrar above) is only
   pulled into the final image if a symbol from it is referenced. Engine startup calls this no-op to
   guarantee the registrations actually run. -#}
namespace Desert::Reflection
{
    void ForceLinkGeneratedReflection() {}
}
// NOLINTEND
