#pragma once
// AUTO-GENERATED by DesertHeaderTool from COMPONENT(...) markers. DO NOT EDIT.
// Regenerated on every build; the marker on the component struct is the one place a block is stated.
{# Excluded from formatting and analysis for the reason Reflection.gen.cpp.tpl gives: every line is the
   template's, and the next build overwrites an edit. -#}
// clang-format off
// NOLINTBEGIN

#include <Engine/Core/Serialize/ReflectedComponentBlocks.hpp>

{% for inc in includes %}#include <{{ inc }}>
{% endfor %}
namespace Desert::Core::Serialize
{
    // Calls `visit` once per row, ordered by key. The rows are distinct types, so a visitor is a generic lambda;
    // `decltype(row)::Data` is the struct a block is read into. ComponentRegistry registers them run by run.
    template <class TVisit>
    void ForEachReflectedComponentBlock( TVisit&& visit )
    {
        using R = ReflectedBlockRun;
{% for c in components %}{% if c.whole %}        visit( ReflectedWholeBlock<::{{ c.fqn }}>{ "{{ c.key }}", "{{ c.typeName }}", R::{{ c.run }} } );
{% else %}        visit( ReflectedMemberBlock<::{{ c.fqn }}, decltype( ::{{ c.fqn }}::{{ c.member }} )>{ "{{ c.key }}", "{{ c.typeName }}", &::{{ c.fqn }}::{{ c.member }}, R::{{ c.run }} } );
{% endif %}{% endfor %}    }
} // namespace Desert::Core::Serialize
// NOLINTEND
