// AUTO-GENERATED by DesertHeaderTool. DO NOT EDIT.
// Regenerated on every build from DESERT_SUBSYSTEM() annotations.
// clang-format off
// NOLINTBEGIN

#include <Common/Core/Subsystems/SubsystemCollection.hpp>
#include <{{ ownerHeader }}>
{% for inc in includes %}#include <{{ inc }}>
{% endfor %}
void {{ ownerNamespace }}::CreateSubsystems( [[maybe_unused]] ::Common::SubsystemCollection<{{ ownerType }}>& collection )
{
{% for subsystem in subsystems %}    collection.Create<::{{ subsystem }}>();
{% endfor %}}

// NOLINTEND
