// DesertAsset {"Kind":"Shader","Guid":"357ab162b17c7ef314a0eb3e33df138b","Versions":{"SHDR":1},"Dependencies":[]}
// GENERATED by the Desert Shader Graph editor — edit the .dgraph, not this file.
Shader "MatProbeUnlit"
{
    Domain Surface

    Properties Binding(1)
    {
        Color     TintA ("TintA") = (0.9, 0.12, 0.08, 1.0)
        Color     TintB ("TintB") = (0.08, 0.25, 0.95, 1.0)
        Float     Blend ("Blend") = 0.0
    }

    State
    {
        Cull Back
        ZTest LEqual
        ZWrite On
    }

    Vertex
    {
        #include <Common/GraphVertex.glslh>
    }

    Fragment
    {
        layout( location = 0 ) in vec2 v_UV;
        layout( location = 0 ) out vec4 o_Color;

        void main()
        {
            vec4 n1 = u_Material.TintA;
            vec4 n2 = u_Material.TintB;
            float n3 = u_Material.Blend;
            vec4 n0 = mix( n1, n2, n3 );
            vec4 albedo = n0;
            o_Color = vec4( albedo.rgb + ( vec4( 0.0 ) ).rgb, albedo.a * ( 1.0 ) );
        }
    }
}
