#!/usr/bin/env python3
"""Generates the mechanical half of .claude/CODEMAP.md from the tree, so it cannot drift.

Measured 2026-09-24: shell search + reading were 50-80 % of every agent task's cost. The map answers the
questions agents searched for: where a subsystem lives, which classes a directory declares, and -- the one
that cost most -- WHICH TEST SUITES AND PROJECTS COMPILE A GIVEN SOURCE (the LandscapeData.cpp trap: every
project compiling it also needs the shader include dir, missed four times).
Hand-written notes (entry points, traps) live between the NOTES markers and are preserved on regeneration.
usage: python3 .claude/tools/gen_codemap.py   (from the repo root)
"""
import collections
import os
import re
import subprocess

OUT = ".claude/CODEMAP.md"
ROOTS = [
    ("Engine", "Desert/Desert/Source/Engine"),
    ("Common", "Desert/Common/Source/Common"),
    ("Editor", "Editor/Source/Editor"),
    ("Runtime", "Runtime/Source"),
    ("Shaders", "Editor/Resources/Shaders"),
    ("Tools", "Tools"),
]
CLASS = re.compile(r"^\s*(?:class|struct)\s+(?:DESERT_API\s+)?([A-Z]\w+)\s*(?:final\s*)?[:{]", re.M)
SRC_IN_PREMAKE = re.compile(r'"%\{wks\.location\}/([^"]+\.(?:cpp|c|mm))"')


def tracked():
    out = subprocess.run(["git", "ls-files"], capture_output=True, text=True).stdout.split("\n")
    return [f for f in out if f]


def main():
    files = tracked()
    code = [f for f in files if f.endswith((".hpp", ".h", ".cpp", ".glslh", ".shader", ".lua", ".py"))]

    # directory -> (file count, lines, classes)
    dirs = collections.defaultdict(lambda: {"n": 0, "lines": 0, "classes": []})
    for f in code:
        d = os.path.dirname(f)
        dirs[d]["n"] += 1
        try:
            text = open(f, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        dirs[d]["lines"] += text.count("\n")
        if f.endswith((".hpp", ".h")):
            dirs[d]["classes"] += CLASS.findall(text)

    # which premake project compiles which engine source
    compiled_by = collections.defaultdict(list)
    for f in files:
        if not f.endswith("premake5.lua"):
            continue
        proj = os.path.basename(os.path.dirname(f))
        text = open(f, encoding="utf-8", errors="replace").read()
        for src in SRC_IN_PREMAKE.findall(text):
            compiled_by[src].append(proj)

    notes = ""
    if os.path.exists(OUT):
        old = open(OUT, encoding="utf-8").read()
        m = re.search(r"<!-- NOTES -->.*?<!-- /NOTES -->", old, re.S)
        if m:
            notes = m.group(0)
    if not notes:
        notes = ("<!-- NOTES -->\n## Notes (hand-written: entry points, traps; preserved on regeneration)\n"
                 "- `LandscapeData.cpp`: every project that compiles it also needs includedir "
                 "`Editor/Resources/Shaders` (missed four times).\n"
                 "- `pointer_ownership_test.cpp` counts conflict on EVERY merge: sum deltas from the merge-base.\n"
                 "- Scene files are paths RELATIVE TO `Editor/` for `--scene`.\n"
                 "<!-- /NOTES -->")

    lines = ["# CODEMAP — read the section of your subsystem BEFORE searching",
             "",
             "Generated by `.claude/tools/gen_codemap.py` from `git ls-files` (do not edit by hand outside NOTES).",
             "Per directory: files, lines, the classes its headers declare. Then: which test suites and projects",
             "compile each engine source -- run exactly those after touching it, and add a new .cpp to all of them.",
             "", notes, ""]
    for title, root in ROOTS:
        lines.append(f"## {title} — `{root}`")
        for d in sorted(k for k in dirs if k == root or k.startswith(root + "/")):
            info = dirs[d]
            rel = d[len(root):].lstrip("/") or "."
            cls = sorted(set(info["classes"]))
            shown = ", ".join(cls[:12]) + (f", … (+{len(cls) - 12})" if len(cls) > 12 else "")
            lines.append(f"- `{rel}` — {info['n']} files, {info['lines']:,} lines" + (f": {shown}" if shown else ""))
        lines.append("")

    lines.append("## Source → suites/projects that compile it (only sources compiled outside their own library)")
    for src in sorted(compiled_by):
        projs = sorted(set(compiled_by[src]))
        lines.append(f"- `{src}` — {len(projs)}: {', '.join(projs)}")
    lines.append("")
    open(OUT, "w", encoding="utf-8").write("\n".join(lines))
    print(f"{OUT}: {len(lines)} lines, {len(dirs)} directories, {len(compiled_by)} sources with explicit compilers")


if __name__ == "__main__":
    main()
