// DesertAsset {"Kind":"Shader","Guid":"5333805ac70dbaa3477448ca41878b10","Versions":{"SHDR":1},"Dependencies":[]}
// GENERATED by the Desert Shader Graph editor — edit the .dgraph, not this file.
Shader "MatConst"
{
    Domain Surface

    State
    {
        Cull Back
        ZTest LEqual
        ZWrite On
    }

    Vertex
    {
        #include <Common/GraphVertex.glslh>
    }

    Fragment
    {
        layout( location = 0 ) in vec2 v_UV;
        layout( location = 0 ) out vec4 o_Color;

        void main()
        {
            vec4 n0 = vec4( 0.95, 0.55, 0.1, 1.0 );
            vec4 albedo = n0;
            o_Color = vec4( albedo.rgb + ( vec4( 0.0 ) ).rgb, albedo.a * ( 1.0 ) );
        }
    }
}
