// DesertAsset {"Kind":"Shader","Guid":"5333805ac70dbaa3477448ca41878b10","Versions":{"SHDR":1},"Dependencies":[]}
// GENERATED by the Desert Shader Graph editor — edit the .dgraph, not this file.
Shader "MatConst"
{
    Domain Surface

    State
    {
        Cull Back
        ZTest LEqual
        ZWrite On
    }

    ShadingModel Unlit

    Surface
    {
        SurfaceOutput EvaluateSurface( SurfaceInput i )
        {
            const vec2 v_UV = i.UV0;
            vec4 n0 = vec4( 0.95, 0.55, 0.1, 1.0 );
            const vec4 albedo = n0;
            SurfaceOutput s = DefaultSurfaceOutput();
            s.BaseColor = vec3( 0.0 );
            s.Emissive = albedo.rgb + ( vec4( 0.0 ) ).rgb;
            s.Opacity = albedo.a * ( 1.0 );
            return s;
        }
    }
}
