// DesertAsset {"Kind":"Shader","Guid":"078fd9f19395a5d5454318bf06410898","Versions":{"SHDR":1},"Dependencies":[]}
// GENERATED by the Desert Shader Graph editor — edit the .dgraph, not this file.
Shader "MatLitConst"
{
    Domain Surface

    State
    {
        Cull Back
        ZTest LEqual
        ZWrite On
    }

    Surface
    {
        SurfaceOutput EvaluateSurface( SurfaceInput i )
        {
            const vec2 v_UV = i.UV0;
            vec4 n0 = vec4( 0.95, 0.55, 0.1, 1.0 );
            const vec4 albedo = n0;
            SurfaceOutput s = DefaultSurfaceOutput();
            s.BaseColor = albedo.rgb;
            s.Metallic = 0.0;
            s.Roughness = 0.5;
            s.AmbientOcclusion = 1.0;
            s.Emissive = ( vec4( 0.0 ) ).rgb;
            s.Opacity = albedo.a * ( 1.0 );
            return s;
        }
    }
}
