// DesertAsset {"Kind":"Shader","Guid":"40293d62f22f46a49912f44c6c024d06","Versions":{"SHDR":1},"Dependencies":[]}
// GENERATED by the Desert Shader Graph editor — edit the .dgraph, not this file.
Shader "MatProbe"
{
    Domain Surface

    Properties Binding(1)
    {
        Color     TintA ("TintA") = (0.9, 0.12, 0.08, 1.0)
        Color     TintB ("TintB") = (0.08, 0.25, 0.95, 1.0)
        Float     Blend ("Blend") = 0.0
    }

    State
    {
        Cull Back
        ZTest LEqual
        ZWrite On
    }

    Vertex
    {
        #define GRAPH_LIT 1
        #include <Common/GraphVertex.glslh>
    }

    Fragment
    {
        layout( location = 0 ) in vec2 v_UV;
        layout( location = 1 ) in vec3 v_Normal;
        layout( location = 2 ) in vec3 v_WorldPos;
        layout( location = 3 ) in vec3 v_CameraPos;
        layout( location = 0 ) out vec4 o_Color;

        #include <Common/GraphSurfaceLighting.glslh>

        void main()
        {
            vec4 n1 = u_Material.TintA;
            vec4 n2 = u_Material.TintB;
            float n3 = u_Material.Blend;
            vec4 n0 = mix( n1, n2, n3 );
            vec4 albedo = n0;
            vec3 N = normalize( v_Normal );
            vec3 view = normalize( v_CameraPos - v_WorldPos );
            vec3 shaded = ShadeGraphSurface( v_WorldPos, N, view, albedo.rgb, 0.0, 0.5, 1.0 );
            o_Color = vec4( shaded + ( vec4( 0.0 ) ).rgb, albedo.a * ( 1.0 ) );
        }
    }
}
