// DesertAsset {"Kind":"Shader","Guid":"357ab162b17c7ef314a0eb3e33df138b","Versions":{"SHDR":1},"Dependencies":[]}
// GENERATED by the Desert Shader Graph editor — edit the .dgraph, not this file.
Shader "MatProbeUnlit"
{
    Domain Surface

    Properties Binding(2)
    {
        Color     TintA ("TintA") = (0.9, 0.12, 0.08, 1.0)
        Color     TintB ("TintB") = (0.08, 0.25, 0.95, 1.0)
        Float     Blend ("Blend") = 0.0
    }

    State
    {
        Cull Back
        ZTest LEqual
        ZWrite On
    }

    Surface
    {
        SurfaceOutput EvaluateSurface( SurfaceInput i )
        {
            const vec2 v_UV = i.UV0;
            vec4 n1 = u_Material.TintA;
            vec4 n2 = u_Material.TintB;
            float n3 = u_Material.Blend;
            vec4 n0 = mix( n1, n2, n3 );
            const vec4 albedo = n0;
            SurfaceOutput s = DefaultSurfaceOutput();
            s.BaseColor = vec3( 0.0 );
            s.Emissive = albedo.rgb + ( vec4( 0.0 ) ).rgb;
            s.Opacity = albedo.a * ( 1.0 );
            return s;
        }
    }
}
