// DesertAsset {"Kind":"Shader","Guid":"7e4ff24afae66800240eb5e3095969fb","Versions":{"SHDR":1},"Dependencies":[]}
// GENERATED by the Desert Shader Graph editor — edit the .dgraph, not this file.
Shader "NewShaderGraph"
{
    Domain Surface

    Properties Binding(1)
    {
        Color     BaseColor ("BaseColor") = (0.8, 0.4, 0.1, 1.0)
    }

    State
    {
        Cull Back
        ZTest LEqual
        ZWrite On
    }

    Vertex
    {
        #include <Common/GraphVertex.glslh>
    }

    Fragment
    {
        layout( location = 0 ) in vec2 v_UV;
        layout( location = 0 ) out vec4 o_Color;

        void main()
        {
            vec4 n0 = u_Material.BaseColor;
            vec4 albedo = n0;
            o_Color = vec4( albedo.rgb + ( vec4( 0.0 ) ).rgb, albedo.a * ( 1.0 ) );
        }
    }
}
