@echo off
setlocal EnableDelayedExpansion
REM Generate project files (premake5 vs2022) and build Desert Engine on Windows.
REM
REM Usage:
REM   scripts\Windows\BuildWindows.bat [Debug^|Release^|Shipping] [--with-tests] [--gen-only] [--no-analyze]
REM
REM Examples:
REM   scripts\Windows\BuildWindows.bat                  Debug build, static analysis on
REM   scripts\Windows\BuildWindows.bat Release          Release build
REM   scripts\Windows\BuildWindows.bat Shipping         what a player gets: no capture, no profiler, no counters
REM   scripts\Windows\BuildWindows.bat Debug --with-tests
REM   scripts\Windows\BuildWindows.bat Debug --no-analyze   skip clang-tidy, and SAY so
REM
REM THE NAME USED TO BE A LIE, AND FOUR SCRIPTS SHARED THE CONFUSION. Until now BuildWindows.bat only
REM ran premake — it generated a solution and built nothing — while CompileWindows.bat was the one
REM that compiled, BuildWindowsWithTests.bat was the same generation with one flag, and
REM BuildWindows_CMake.bat pointed a CMake generator at a directory with no CMakeLists.txt in it.
REM Nothing in those names said which of them a person should run. This script now does what
REM scripts/MacOS/BuildMacOS.sh does, with the same arguments, and the other three are gone.
REM
REM There is also no PAUSE here. Two of the deleted scripts ended in one, which is fine for a
REM double-click and hangs for ever when another script or CI calls it.

cd /d "%~dp0..\.."
set "ROOT=%CD%"
set "VSWHERE=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"

set "CONFIG=Debug"
set "PREMAKE_ARGS="
set "GEN_ONLY=0"
set "ANALYZE=1"

REM WHERE THE ANALYSER ATTACHES. One path, named once. Its exit codes ARE its interface — 0 clean,
REM 1 findings, 2 the gate could not run — so this script reads its status and never its output: a
REM gate that cannot run prints nothing, which is byte-identical to a gate that found nothing.
REM
REM SPELLED THROUGH %ROOT% AND NOT %~dp0..\, deliberately: Desert/Tests/Tools/BuildScriptContract
REM checks that every "scripts/..." path written anywhere under scripts/ resolves to a real file, and
REM it finds those paths by their text. A path assembled out of %~dp0 and ".." is invisible to that
REM check — it would be a reference no gate can see, which is the thing the gate exists to prevent.
set "ANALYZER=%ROOT%\scripts\CI\CheckTidy.bat"

:parse_args
if "%~1"=="" goto args_done
if /I "%~1"=="Debug"        (set "CONFIG=Debug"          & shift & goto parse_args)
if /I "%~1"=="Release"      (set "CONFIG=Release"        & shift & goto parse_args)
REM SHIPPING WAS REJECTED HERE, ON THE PLATFORM THE GAME SHIPS FOR. The configuration arrived with its
REM macOS wrapper taught the word (scripts/MacOS/BuildMacOS.sh) and this one not, so
REM `BuildWindows.bat Shipping` answered "[ERROR] Unknown argument: Shipping" -- while the packager's
REM own "Runtime binary not found" message is what sends people here to build that configuration.
REM Two dead ends in a row is how a configuration stops being used at all.
if /I "%~1"=="Shipping"     (set "CONFIG=Shipping"       & shift & goto parse_args)
if /I "%~1"=="--with-tests" (set "PREMAKE_ARGS=--with-tests" & shift & goto parse_args)
if /I "%~1"=="--gen-only"   (set "GEN_ONLY=1"            & shift & goto parse_args)
if /I "%~1"=="--no-analyze" (set "ANALYZE=0"             & shift & goto parse_args)
echo [ERROR] Unknown argument: %~1 1>&2
echo         Usage: scripts\Windows\BuildWindows.bat [Debug^|Release^|Shipping] [--with-tests] [--gen-only] [--no-analyze] 1>&2
exit /b 1
:args_done

REM premake5 from PATH if the developer has one, otherwise the copy Setup.bat fetched. The deleted
REM Python wrapper hard-coded vendor\bin\premake5.exe and could therefore not build on a machine where
REM Setup.bat had found premake5 on PATH and never written that file.
set "PREMAKE="
where premake5 >NUL 2>&1
if not errorlevel 1 set "PREMAKE=premake5"
if not defined PREMAKE if exist "%ROOT%\vendor\bin\premake5.exe" set "PREMAKE=%ROOT%\vendor\bin\premake5.exe"
if not defined PREMAKE (
    echo [ERROR] premake5 not found on PATH or in vendor\bin. Run scripts\Windows\Setup.bat first. 1>&2
    exit /b 1
)

REM NO GenVersion.bat CALL HERE, AND THE ABSENCE IS THE FIX. The build identity is generated by
REM Common.vcxproj's PreBuildEvent, which runs on every build. Refreshing it here as well would put
REM the refresh in two places, and the one that runs first would hide a hook that had stopped
REM working: a missing header is a compile error, a stale one is a lie.

echo --- Generating project files ^(premake5 vs2022^)
"%PREMAKE%" vs2022 %PREMAKE_ARGS%
if errorlevel 1 (
    echo [ERROR] premake5 vs2022 failed. 1>&2
    exit /b 1
)

if "%GEN_ONLY%"=="1" (
    echo === Desert.sln generated ===
    exit /b 0
)

REM MSBuild from the Visual Studio instance vswhere reports, falling back to a plain `msbuild` for a
REM Developer Command Prompt. Checked by EXIT CODE below, never by scraping the output.
set "MSBUILD="
if exist "%VSWHERE%" (
    for /f "usebackq delims=" %%i in (`"%VSWHERE%" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe 2^>NUL`) do set "MSBUILD=%%i"
)
if not defined MSBUILD (
    where msbuild >NUL 2>&1
    if not errorlevel 1 set "MSBUILD=msbuild"
)
if not defined MSBUILD (
    echo [ERROR] MSBuild.exe not found. Run scripts\Windows\Setup.bat, which installs the MSVC 1>&2
    echo         v143 toolset and MSBuild, or open a Developer Command Prompt. 1>&2
    exit /b 1
)

echo --- Building ^(%CONFIG% ^| x64^)
echo     Tip: close Editor.exe first — a running one makes the link fail with LNK1168.
"%MSBUILD%" "%ROOT%\Desert.sln" -p:Configuration=%CONFIG% -p:Platform=x64 -m -v:minimal
if errorlevel 1 (
    echo [ERROR] build failed ^(%CONFIG%^). 1>&2
    exit /b 1
)

echo.
echo === Build complete: build\Bin\%CONFIG% ===

REM ---------------------------------------------------------------------------
REM Static analysis.
REM
REM THE ONLY OUTCOME THAT MAY BE SILENT IS THE ONE WHERE IT RAN. Every other path prints a line saying
REM the analyser did not run and why, because a check skipped without saying so is worse than one that
REM was never added: the build looks exactly as it does when the code is clean, so the absence is
REM invisible for as long as nobody goes looking. This platform has already paid for that shape once —
REM cmd ate the digit in `set ERROR=0>>` and the Windows test runner could not report a failure at all
REM before 2026-08-15, while every run looked green.
REM
REM NOT UNDER CI: a gate belongs in its own job, where its verdict is separable from the build's,
REM exactly as the clang-format gate already is. Windows Debug measured 73-93 minutes against a
REM 150-minute ceiling and has been cancelled by its own timeout twice; a cancelled job reports as
REM `cancelled`, which looks like nothing being wrong.
REM ---------------------------------------------------------------------------
if "%ANALYZE%"=="0" (
    echo !!! static analysis SKIPPED: --no-analyze was passed. Nothing was checked by clang-tidy.
    endlocal
    exit /b 0
)
if defined CI (
    echo !!! static analysis SKIPPED: running under CI, where the clang-tidy gate is its own job.
    endlocal
    exit /b 0
)
if not exist "%ANALYZER%" (
    REM NOT IMPLEMENTED ON THIS PLATFORM is a THIRD state, and it is not the same as COULD NOT RUN.
    REM
    REM "Could not run" is transient — a missing binary, a wrong version, a broken database — and it
    REM must refuse, because it is indistinguishable from "ran and found nothing" by output alone.
    REM This is not that. The Windows entry point has never been written: the gate reads a compile
    REM database built from premake's gmake2 makefiles, and a Windows build is MSBuild/MSVC, so the
    REM analyser would read a DIFFERENT PROGRAM than the one being shipped. Refusing until somebody
    REM writes it does not produce analysis — it produces a platform whose build always fails, which
    REM is how "--no-analyze" becomes the command everybody types and the gate dies unnoticed.
    REM
    REM So it says so on every build, loudly, and proceeds. What keeps this from becoming a permanent
    REM silent skip is not the exit code: it is the row in BuildScriptContract's kPendingReferences,
    REM which names the owing task and REDDENS the moment scripts\CI\CheckTidy.bat appears.
    echo. 1>&2
    echo !!! static analysis NOT AVAILABLE ON WINDOWS YET: "%ANALYZER%" does not exist. 1>&2
    echo     Nothing was checked by clang-tidy. This is a known gap, not a failure of your build: 1>&2
    echo     the gate needs an MSVC compile database, which is its own task. 1>&2
    echo     On macOS the same build DOES analyse, so a change that only builds here is unchecked. 1>&2
    echo. 1>&2
    goto after_analysis
)

echo --- Static analysis ^(clang-tidy, changed lines^)
call "%ANALYZER%"
set "ANALYZER_RC=%ERRORLEVEL%"
if "%ANALYZER_RC%"=="0" (
    echo === clang-tidy: clean ===
    endlocal
    exit /b 0
)
if "%ANALYZER_RC%"=="1" (
    echo clang-tidy reported findings in the lines you changed ^(see above^). 1>&2
    endlocal
    exit /b 1
)
REM Exit 2 and anything unexpected are the same thing here: the gate produced no verdict, and
REM "no verdict" must never be reported as "clean".
echo clang-tidy COULD NOT RUN ^(exit %ANALYZER_RC%^) — an environment failure, not a clean analysis. 1>&2
echo   The binaries in build\Bin\%CONFIG% are still valid. 1>&2
endlocal
exit /b 1

:after_analysis
REM Reached ONLY by the not-implemented-on-this-platform branch above. The build succeeded and was
REM not analysed, and the line that says so has already been printed to stderr.
endlocal
exit /b 0
